#!/bin/sh
 
# Exit on error
set -e
 
# Source debconf library.
. /usr/share/debconf/confmodule
 
# Ask user for custom install path
db_input low madlib/installpath || true
 
# Show interface
db_go || true
