#!/bin/sh
#
# coding=utf-8
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# remove symlinks created during rpm install

# Source debconf library.
. /usr/share/debconf/confmodule

# Fetching configuration from debconf
db_get madlib/installpath
MADLIB_INSTALL_PATH=$RET

find $MADLIB_INSTALL_PATH/madlib/Current -depth -type l -exec rm {} \; 2>/dev/null
find $MADLIB_INSTALL_PATH/madlib/bin -depth -type l -exec rm {} \; 2>/dev/null
find $MADLIB_INSTALL_PATH/madlib/doc -depth -type l -exec rm {} \; 2>/dev/null

# remove "Versions" directory if it's empty
rmdir $MADLIB_INSTALL_PATH/madlib/Versions 2>/dev/null
exit 0
