#!/bin/sh
#
# coding=utf-8
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Source debconf library.
. /usr/share/debconf/confmodule

MADLIB_INSTALL_PATH="InstallPathNotFound"

# Fetching configuration from debconf
db_get madlib/installpath
MADLIB_INSTALL_PATH=$RET

if [ -d "$MADLIB_INSTALL_PATH/madlib/Versions" ];
then
    cp -r $MADLIB_INSTALL_PATH/madlib/Versions/ $MADLIB_INSTALL_PATH/madlib/Versions.bak/
fi
