FROM njayaram/madlib:postgres_9.6

### Build MADlib
ADD ./ /incubator-madlib
RUN	 cd incubator-madlib && \
     mkdir build && \
	 cd build && \
	 cmake .. && \
	 make && \
	 make install

##################################################################################################
################# USEFUL COMMANDS ##################
## Build the image from this docker file:
# docker build -t madlib -f tool/docker/postgres/Dockerfile_9_6 .

### Steps to use the image for installing MADlib, building changed source code:
## Run the container, mounting the source code's folder to the container. For example:
# 1) docker run -d -it --name madlib -v (path-to-incubator-madlib)/src:/incubator-madlib/src madlib

## When the container is up, connect to it and execute (Install MADlib):
# 2) docker exec -it madlib /incubator-madlib/build/src/bin/madpack -p postgres -c postgres/postgres@localhost:5432/postgres install

## Go into the container to build and run commands like install-check for modules:
# 3) docker exec -it madlib bash

## The above command gives us terminal access to the container, run commands such as:
# - cd /incubator-madlib/build
# - make (This can be run after changing code in the incubator-madlib source code)
# - src/bin/madpack -p postgres  -c postgres/postgres@localhost:5432/postgres install-check -t svm
## Install or reinstall MADlib if required:
# - src/bin/madpack -p postgres  -c postgres/postgres@localhost:5432/postgres install
# - src/bin/madpack -p postgres  -c postgres/postgres@localhost:5432/postgres reinstall


### Common docker commands:
## Kill and remove containers:
# - docker kill madlib
# - docker rm madlib
