FROM postgres:9.6

### Get postgres specific add-ons
RUN apt-get update && apt-get install -y  wget \
                       build-essential \
                       postgresql-server-dev-9.6 \
                       postgresql-plpython-9.6 \
                       openssl \
                       libssl-dev \
                       libboost-all-dev \
                       m4 \
                       wget \
                       vim \
                       pgxnclient

### Build custom CMake with SSQL support
RUN wget https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz && \
      tar -zxvf cmake-3.5.2.tar.gz && \
      cd cmake-3.5.2 && \
      sed -i 's/-DCMAKE_BOOTSTRAP=1/-DCMAKE_BOOTSTRAP=1 -DCMAKE_USE_OPENSSL=ON/g' bootstrap && \
      ./configure &&  \
      make -j2 && \
      make install
